Demos/ZeusAlipayMvcApp/Models/ErrorViewModel.cs
using System;

namespace ZeusAlipayMvcApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Demos/ZeusAlipayMvcApp/Controllers/AuthTokenController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace ZeusAlipayMvcApp.Controllers
{
    public class AuthTokenController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Index([FromForm]string AppId)
        {
            string redirectUri = HttpContext.Request.Scheme + "://" + HttpContext.Request.Host + "/GetToken";
            string RequestPath = $"https://openauth.alipay.com/oauth2/appToAppAuth.htm?app_id={AppId}&redirect_uri=" + redirectUri;
            return Redirect(RequestPath);
        }
        [HttpGet("GetToken")]
        public IActionResult GetToken(string app_id, string app_auth_code)
        {
            return Json("AppId =" + app_id + ",app_auth_code="  + app_auth_code);
        }
    }
}

Demos/ZeusAlipayMvcApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ZeusAlipayMvcApp.Models;

namespace ZeusAlipayMvcApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Demos/ZeusAlipayMvcApp/Views/AuthToken/GetToken.cshtml
@model string
@{
    ViewData["Title"] = "GetToken";
}

<h1>GetToken</h1>
<p>@Model</p>

Demos/ZeusAlipayMvcApp/Views/AuthToken/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Create Alipay token</h1>

<form method="post">
    <input name="AppId" type="text" />
    <button type="submit">Submit</button>
</form>

Demos/ZeusAlipayMvcApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <a class="btn btn-outline-dark" asp-controller="AuthToken" asp-action="Index">Click me into AuthToken!</a>
</div>

Demos/ZeusAlipayMvcApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ZeusAlipayMvcApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZeusAlipayMvcApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ZeusAlipayMvcApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>